IN_PROGRESS_MARKER = "IN_PROGRESS"
DONE_MARKER = "DONE.txt"
ABORTED_MARKER = "ABORTED.txt"

MODEL_CHECKPOINT = "model.pt"
MODEL_B0_CHECKPOINT = "model_b0.pt"
SCORING_SENTINEL = "SCORING_DONE.txt"
SCORING_MANIFEST_FILE = "scoring_manifest.json"
METRICS_FILE = "metrics.json"
METRICS_TMP_FILE = "metrics.json.tmp"
REPORTING_AUDIT_FILE = "reporting_audit.json"
SCALER_FILE = "scaler.pkl"
MANIFEST_FILE = "manifest.json"
LOG_FILENAME = "datp.log"
