OUTPUTS_DIR = "outputs"
RESULTS_DIR = "results"
CHECKPOINTS_DIR = "checkpoints"
SCORES_DIR = "scores"
LOGS_DIR = "logs"
CONSOLE_LOGS_DIR = "console_logs"
ANALYSIS_DIR = "analysis"
FIGURES_DIR = "figures"
TABLES_DIR = "tables"

CONFUSION_MATRICES_DIR = "confusion_matrices"
